--------------------------------------------------------
-- Archivo creado  - miércoles-agosto-05-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence SP_CONTROL
--------------------------------------------------------

   CREATE SEQUENCE  "PY"."SP_CONTROL"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SQ_CARGO
--------------------------------------------------------

   CREATE SEQUENCE  "PY"."SQ_CARGO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SQ_CLASIF_ORGANIZACION
--------------------------------------------------------

   CREATE SEQUENCE  "PY"."SQ_CLASIF_ORGANIZACION"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SQ_DOCUMENTOS
--------------------------------------------------------

   CREATE SEQUENCE  "PY"."SQ_DOCUMENTOS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SQ_ESTADO_CIVIL
--------------------------------------------------------

   CREATE SEQUENCE  "PY"."SQ_ESTADO_CIVIL"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SQ_EXPEDIENTE
--------------------------------------------------------

   CREATE SEQUENCE  "PY"."SQ_EXPEDIENTE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SQ_ORGANIZACION
--------------------------------------------------------

   CREATE SEQUENCE  "PY"."SQ_ORGANIZACION"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SQ_ORGANO_DIRECTIVA
--------------------------------------------------------

   CREATE SEQUENCE  "PY"."SQ_ORGANO_DIRECTIVA"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SQ_ORGANO_DIRECTIVA_DET
--------------------------------------------------------

   CREATE SEQUENCE  "PY"."SQ_ORGANO_DIRECTIVA_DET"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SQ_PERSONA
--------------------------------------------------------

   CREATE SEQUENCE  "PY"."SQ_PERSONA"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SQ_SEXO
--------------------------------------------------------

   CREATE SEQUENCE  "PY"."SQ_SEXO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SQ_TIPO_DOC_EXP
--------------------------------------------------------

   CREATE SEQUENCE  "PY"."SQ_TIPO_DOC_EXP"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SQ_TIPO_DOCUMENTO
--------------------------------------------------------

   CREATE SEQUENCE  "PY"."SQ_TIPO_DOCUMENTO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SQ_TIPO_ORGANIZACION
--------------------------------------------------------

   CREATE SEQUENCE  "PY"."SQ_TIPO_ORGANIZACION"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SQ_USUARIOS
--------------------------------------------------------

   CREATE SEQUENCE  "PY"."SQ_USUARIOS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table CARGO
--------------------------------------------------------

  CREATE TABLE "PY"."CARGO" 
   (	"ID_CARGO" NUMBER, 
	"NOMBRE" VARCHAR2(60 BYTE), 
	"ESTADO" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CLASIF_ORGANIZACION
--------------------------------------------------------

  CREATE TABLE "PY"."CLASIF_ORGANIZACION" 
   (	"ID_CLASIF_ORG" NUMBER, 
	"NOMBRE" VARCHAR2(60 BYTE), 
	"ESTADO" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CONTROL
--------------------------------------------------------

  CREATE TABLE "PY"."CONTROL" 
   (	"ID_CONTROL" NUMBER, 
	"USUARIO" VARCHAR2(50 BYTE), 
	"TABLA" VARCHAR2(50 BYTE), 
	"ACCION" VARCHAR2(40 BYTE), 
	"DATOS" VARCHAR2(500 BYTE), 
	"FECHA" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DOCUMENTOS
--------------------------------------------------------

  CREATE TABLE "PY"."DOCUMENTOS" 
   (	"ID_DOCUMENTO" NUMBER, 
	"ID_ORGANIZACION" NUMBER, 
	"NOMBRE" VARCHAR2(60 BYTE), 
	"ID_TIPO_DOC_EXP" NUMBER, 
	"ARCHIVO" BLOB, 
	"ESTADO" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("ARCHIVO") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table ESTADO_CIVIL
--------------------------------------------------------

  CREATE TABLE "PY"."ESTADO_CIVIL" 
   (	"ID_ESTADO_CIVIL" NUMBER, 
	"NOMBRE" VARCHAR2(60 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EXPEDIENTE
--------------------------------------------------------

  CREATE TABLE "PY"."EXPEDIENTE" 
   (	"ID_EXPEDIENTE" NUMBER, 
	"ID_SOLICITANTE" NUMBER, 
	"FECHA_REGISTRO" DATE, 
	"ID_USUARIO_REVISION" NUMBER, 
	"FECHA_REVISION" DATE, 
	"ESTADO" CHAR(1 BYTE), 
	"OBSERVACIONES" VARCHAR2(120 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ORGANIZACION
--------------------------------------------------------

  CREATE TABLE "PY"."ORGANIZACION" 
   (	"ID_ORGANIZACION" NUMBER, 
	"ID_EXPEDIENTE" NUMBER, 
	"NOMBRE_ORG" VARCHAR2(60 BYTE), 
	"ID_TIPO_ORG" NUMBER, 
	"NUM_PART_REGISTRAL" VARCHAR2(10 BYTE), 
	"FECHA_INICIO" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ORGANIZACION_PERSONA
--------------------------------------------------------

  CREATE TABLE "PY"."ORGANIZACION_PERSONA" 
   (	"ID_ORGANIZACION" NUMBER, 
	"ID_ASOCIADO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ORGANO_DIRECTIVA
--------------------------------------------------------

  CREATE TABLE "PY"."ORGANO_DIRECTIVA" 
   (	"ID_ORGANO_DIRECTIVO" NUMBER, 
	"ID_ORGANIZACION" NUMBER, 
	"FEC_INICIO" DATE, 
	"FEC_FIN" DATE, 
	"TIEMPO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ORGANO_DIRECTIVA_DET
--------------------------------------------------------

  CREATE TABLE "PY"."ORGANO_DIRECTIVA_DET" 
   (	"ID_ORGANO_DIRECTIVO_DET" NUMBER, 
	"ID_ORGANO_DIRECTIVO" NUMBER, 
	"ID_PERSONA" NUMBER, 
	"ID_CARGO" NUMBER, 
	"ESTADO" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PERSONA
--------------------------------------------------------

  CREATE TABLE "PY"."PERSONA" 
   (	"ID_PERSONA" NUMBER, 
	"NOMBRES" VARCHAR2(60 BYTE), 
	"APELLIDO_PATER" VARCHAR2(30 BYTE), 
	"APELLIDO_MATER" VARCHAR2(30 BYTE), 
	"ID_TIPO_DOC" NUMBER, 
	"NUMERO_DOC" VARCHAR2(9 BYTE), 
	"ID_SEXO" NUMBER, 
	"FEC_NAC" DATE, 
	"TELEFONO" VARCHAR2(9 BYTE), 
	"CORREO" VARCHAR2(120 BYTE), 
	"ID_ESTADO_CIVIL" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SEXO
--------------------------------------------------------

  CREATE TABLE "PY"."SEXO" 
   (	"ID_SEXO" NUMBER, 
	"NOMBRE" VARCHAR2(60 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TIPO_DOC_EXP
--------------------------------------------------------

  CREATE TABLE "PY"."TIPO_DOC_EXP" 
   (	"ID_TIPO_DOC_EXP" NUMBER, 
	"NOMBRE" VARCHAR2(60 BYTE), 
	"ESTADO" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TIPO_DOCUMENTO
--------------------------------------------------------

  CREATE TABLE "PY"."TIPO_DOCUMENTO" 
   (	"ID_TIPO_DOC" NUMBER, 
	"NOMBRE" VARCHAR2(60 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TIPO_ORGANIZACION
--------------------------------------------------------

  CREATE TABLE "PY"."TIPO_ORGANIZACION" 
   (	"ID_TIPO_ORG" NUMBER, 
	"NOMBRE" VARCHAR2(60 BYTE), 
	"ID_CLASIF_ORG" NUMBER, 
	"ESTADO" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USUARIOS
--------------------------------------------------------

  CREATE TABLE "PY"."USUARIOS" 
   (	"ID_USUARIOS" NUMBER, 
	"NOMBRE" VARCHAR2(60 BYTE), 
	"ESTADO" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into PY.CARGO
SET DEFINE OFF;
REM INSERTING into PY.CLASIF_ORGANIZACION
SET DEFINE OFF;
Insert into PY.CLASIF_ORGANIZACION (ID_CLASIF_ORG,NOMBRE,ESTADO) values ('1','ORGANIZACION DE VECINOS','A');
REM INSERTING into PY.CONTROL
SET DEFINE OFF;
REM INSERTING into PY.DOCUMENTOS
SET DEFINE OFF;
REM INSERTING into PY.ESTADO_CIVIL
SET DEFINE OFF;
REM INSERTING into PY.EXPEDIENTE
SET DEFINE OFF;
Insert into PY.EXPEDIENTE (ID_EXPEDIENTE,ID_SOLICITANTE,FECHA_REGISTRO,ID_USUARIO_REVISION,FECHA_REVISION,ESTADO,OBSERVACIONES) values ('1','1',to_date('29/07/20','DD/MM/RR'),null,null,'1',null);
Insert into PY.EXPEDIENTE (ID_EXPEDIENTE,ID_SOLICITANTE,FECHA_REGISTRO,ID_USUARIO_REVISION,FECHA_REVISION,ESTADO,OBSERVACIONES) values ('2','1',to_date('29/07/20','DD/MM/RR'),null,null,'1',null);
Insert into PY.EXPEDIENTE (ID_EXPEDIENTE,ID_SOLICITANTE,FECHA_REGISTRO,ID_USUARIO_REVISION,FECHA_REVISION,ESTADO,OBSERVACIONES) values ('3','1',to_date('01/08/20','DD/MM/RR'),'1',to_date('05/08/20','DD/MM/RR'),'2',null);
REM INSERTING into PY.ORGANIZACION
SET DEFINE OFF;
Insert into PY.ORGANIZACION (ID_ORGANIZACION,ID_EXPEDIENTE,NOMBRE_ORG,ID_TIPO_ORG,NUM_PART_REGISTRAL,FECHA_INICIO) values ('1','1','LOS JORGITOS','1','1011121314',to_date('01/08/20','DD/MM/RR'));
Insert into PY.ORGANIZACION (ID_ORGANIZACION,ID_EXPEDIENTE,NOMBRE_ORG,ID_TIPO_ORG,NUM_PART_REGISTRAL,FECHA_INICIO) values ('2','2','LOS VALVERDES','1','1011121315',to_date('01/08/20','DD/MM/RR'));
Insert into PY.ORGANIZACION (ID_ORGANIZACION,ID_EXPEDIENTE,NOMBRE_ORG,ID_TIPO_ORG,NUM_PART_REGISTRAL,FECHA_INICIO) values ('3','3','LOS VILLARREALES','1','1011121316',to_date('01/08/20','DD/MM/RR'));
REM INSERTING into PY.ORGANIZACION_PERSONA
SET DEFINE OFF;
REM INSERTING into PY.ORGANO_DIRECTIVA
SET DEFINE OFF;
Insert into PY.ORGANO_DIRECTIVA (ID_ORGANO_DIRECTIVO,ID_ORGANIZACION,FEC_INICIO,FEC_FIN,TIEMPO) values ('1','1',to_date('01/08/20','DD/MM/RR'),to_date('31/07/22','DD/MM/RR'),'5');
Insert into PY.ORGANO_DIRECTIVA (ID_ORGANO_DIRECTIVO,ID_ORGANIZACION,FEC_INICIO,FEC_FIN,TIEMPO) values ('2','2',to_date('01/08/20','DD/MM/RR'),to_date('31/07/22','DD/MM/RR'),'5');
REM INSERTING into PY.ORGANO_DIRECTIVA_DET
SET DEFINE OFF;
REM INSERTING into PY.PERSONA
SET DEFINE OFF;
Insert into PY.PERSONA (ID_PERSONA,NOMBRES,APELLIDO_PATER,APELLIDO_MATER,ID_TIPO_DOC,NUMERO_DOC,ID_SEXO,FEC_NAC,TELEFONO,CORREO,ID_ESTADO_CIVIL) values ('1','Esteban Josue','Valverde','Ayte','1','72480509','1',to_date('14/10/95','DD/MM/RR'),null,null,null);
REM INSERTING into PY.SEXO
SET DEFINE OFF;
Insert into PY.SEXO (ID_SEXO,NOMBRE) values ('1','MASCULINO');
REM INSERTING into PY.TIPO_DOC_EXP
SET DEFINE OFF;
REM INSERTING into PY.TIPO_DOCUMENTO
SET DEFINE OFF;
Insert into PY.TIPO_DOCUMENTO (ID_TIPO_DOC,NOMBRE) values ('1','DNI');
REM INSERTING into PY.TIPO_ORGANIZACION
SET DEFINE OFF;
Insert into PY.TIPO_ORGANIZACION (ID_TIPO_ORG,NOMBRE,ID_CLASIF_ORG,ESTADO) values ('1','ASOCIACION DE PROPIETARIOS','1','A');
REM INSERTING into PY.USUARIOS
SET DEFINE OFF;
Insert into PY.USUARIOS (ID_USUARIOS,NOMBRE,ESTADO) values ('1','Esteban','A');
--------------------------------------------------------
--  DDL for Trigger TR_PERSONA
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PY"."TR_PERSONA" BEFORE INSERT OR DELETE
OR UPDATE ON persona FOR EACH ROW BEGIN
IF INSERTING THEN 
INSERT INTO control VALUES (SSQ_CONTROL.NEXTVAL, USER, 
'Persona',
'Insert’,
‘id:’ ||:new.id_persona || ‘NOMBRES: ’ || :new.nombres || ‘APELLIDO_PATER:’ || :new.apellido_pater || ‘APELLIDO_MATER’ || :new.apellido_mater || ‘ id_tipo_doc’ || :new.id_tipo_doc  || ‘NUMERO_DOC’ || :new.numero_doc || ‘id_sexo’ || :new.id_sexo || ‘FEC_NAC’ || :new.fec_nac || ‘TELEFONO’ || :new.telefono || ‘CORREO’ || :new.coreo || ‘id_estado_civil’ || :new.id_estado_civil, sysdate);

ELSIF DELETING THEN
INSERT INTO control
VALUES (SQ_CONTROL.NEXTVAL,
USER,
‘Persona’,
‘delete’,
‘id:’ ||:old.id_persona || ‘NOMBRES: ’ || :old.nombres || ‘APELLIDO_PATER:’ || :old.apellido_pater || ‘APELLIDO_MATER:’ || :old.apellido_mater || ‘id_tipo_doc:’ || :old.id_tipo_doc || ‘NUMERO_DOC:’ || :old.numero_doc || ‘id_sexo:’ || :old.id_sexo || ‘FEC_NAC:’ || :old.fec_nac || ‘TELEFONO:’ || :old.telefono || ‘correo:’ || :old.correo || ‘id_estado_civil:’ || :old.id_estado_civil, sysdate);

ELSIF UPDATING THEN
INSERT INTO control
VALUES (SQ_CONTROL.NEXTVAL,
USER,
‘Persona’,
‘update’,
‘id:’ ||:old.id_persona || ‘ Antes: ( ‘ || :old. nombres || ’ ,  ‘ || :old.apellido_pater || ’ , ‘ || :old.apellido_mater ||  , ‘ || :old.id_tipo_doc || ’ , ‘ || :old.numero_doc ||  ’ , ‘ || :old.id_sexo || ’ , ‘ || :old.fec_nac || ’ , ‘ || :old.telefono || ’ , ‘ || :old.correo || ’ , ‘ || :old.id_estado_civil || ’) Ahora(‘ || :new.nombres || ’ ,  ‘ || :new.apellido_pater || ’ , ‘|| :new.apellido_mater || ’ , ‘|| :new.id_tipo_doc || ’, ‘ || new.numero.doc || ’ , ‘ || :old.id_sexo || ’ , ‘ || :old.fec_nac || ’ , ‘ || :old.telefono || ’ , ‘ || :old.correo || ’ , ‘ || :old.id_estado_civil || ’,  sysdate);
END IF;
END; 
/
ALTER TRIGGER "PY"."TR_PERSONA" ENABLE;
--------------------------------------------------------
--  DDL for Procedure SP_AGREGAR_CARGO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "PY"."SP_AGREGAR_CARGO" 
(NOMBRE VARCHAR2)
  	IS     	 
  	BEGIN
      	INSERT INTO CARGO
      	VALUES(SQ_CARGO.NEXTVAL,NOMBRE,'A');
  	END SP_AGREGAR_CARGO;

/
--------------------------------------------------------
--  DDL for Procedure SP_AGREGAR_CLASIF_ORGANIZACION
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "PY"."SP_AGREGAR_CLASIF_ORGANIZACION" 
       (NOMBRE VARCHAR2 )
        IS     	 
        BEGIN
            INSERT INTO clasif_organizacion
            VALUES(SQ_CLASIF_ORGANIZACION.nextval,NOMBRE, 'A');
        END SP_AGREGAR_CLASIF_ORGANIZACION;

/
--------------------------------------------------------
--  DDL for Procedure SP_AGREGAR_DOCUMENTOS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "PY"."SP_AGREGAR_DOCUMENTOS" 
(ID_ORGANIZACION NUMBER, NOMBRE VARCHAR2, ID_TIPO_DOC_EXP NUMBER , ARCHIVO BLOB   )
IS
BEGIN
INSERT INTO DOCUMENTOS VALUES(SQ_DOCUMENTOS.NEXTVAL, ID_ORGANIZACION, NOMBRE, ID_TIPO_DOC_EXP, EMPTY_BLOB(),'A');
END SP_AGREGAR_DOCUMENTOS;

/
--------------------------------------------------------
--  DDL for Procedure SP_AGREGAR_ESTADO_CIVIL
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "PY"."SP_AGREGAR_ESTADO_CIVIL" 
(NOMBRE VARCHAR2)
IS
BEGIN
INSERT INTO estado_civil VALUES(SQ_ESTADO_CIVIL.nextval, NOMBRE);
END SP_AGREGAR_ESTADO_CIVIL;

/
--------------------------------------------------------
--  DDL for Procedure SP_AGREGAR_EXPEDIENTE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "PY"."SP_AGREGAR_EXPEDIENTE" 
(ID_SOLICITANTE NUMBER, FECHA_REGISTRO DATE, ID_USUARIO_REVISION NUMBER , FECHA_REVISION DATE, OBSERVACIONES VARCHAR2)
IS
BEGIN
INSERT INTO EXPEDIENTE VALUES(SQ_EXPEDIENTE.NEXTVAL,ID_SOLICITANTE , FECHA_REGISTRO, ID_USUARIO_REVISION,  FECHA_REVISION , 0 , OBSERVACIONES );
END SP_AGREGAR_EXPEDIENTE;

/
--------------------------------------------------------
--  DDL for Procedure SP_AGREGAR_ORGANIZACION
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "PY"."SP_AGREGAR_ORGANIZACION" 
(NOMBRE_ORG VARCHAR2, ID_TIPO_ORG NUMBER , NUM_PART_REGISTRAL VARCHAR2 , FECHA DATE)
IS 
BEGIN
INSERT INTO organizacion VALUES(SQ_ORGANIZACION.NEXTVAL, SQ_EXPEDIENTE.CURRVAL, NOMBRE_ORG, ID_TIPO_ORG , NUM_PART_REGISTRAL, FECHA);
END SP_AGREGAR_ORGANIZACION;

/
--------------------------------------------------------
--  DDL for Procedure SP_AGREGAR_ORGANO_DIRECTIVA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "PY"."SP_AGREGAR_ORGANO_DIRECTIVA" 
(ID_ORGANIZACION NUMBER, fecha_ini date, fecha_fin date , tiempo number )
is
begin
INSERT INTO ORGANO_DIRECTIVA VALUES(SQ_ORGANO_DIRECTIVA.NEXTVAL, ID_ORGANIZACION , FECHA_INI, FECHA_FIN, TIEMPO);
END SP_AGREGAR_ORGANO_DIRECTIVA;

/
--------------------------------------------------------
--  DDL for Procedure SP_AGREGAR_ORGANO_DIRE_DET
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "PY"."SP_AGREGAR_ORGANO_DIRE_DET" 
(ID_ORGANO_DIRECTIVO NUMBER, ID_PERSONA NUMBER, ID_CARGO NUMBER )
IS
BEGIN
INSERT INTO ORGANO_DIRECTIVA_DET VALUES(SQ_ORGANO_DIRECTIVA_DET.NEXTVAL,ID_ORGANO_DIRECTIVO, ID_PERSONA ,ID_CARGO, 'A');
END SP_AGREGAR_ORGANO_DIRE_DET;

/
--------------------------------------------------------
--  DDL for Procedure SP_AGREGAR_PERSONA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "PY"."SP_AGREGAR_PERSONA" 
(NOMBRES VARCHAR2 , APELLIDO_PATER VARCHAR2 , APELLIDO_MATER VARCHAR2, ID_TIPO_DOC NUMBER, NUMERO_DOC VARCHAR2, ID_SEXO NUMBER, FEC_NAC DATE, TELEFONO VARCHAR2, CORREO VARCHAR2 , ID_ESTADO_CIVIL NUMBER )
IS 
BEGIN
INSERT INTO PERSONA VALUES(SQ_PERSONA.NEXTVAL, NOMBRES , APELLIDO_PATER , APELLIDO_MATER, ID_TIPO_DOC ,NUMERO_DOC, ID_SEXO , FEC_NAC,  TELEFONO , CORREO , ID_ESTADO_CIVIL  );
END SP_AGREGAR_PERSONA;

/
--------------------------------------------------------
--  DDL for Procedure SP_AGREGAR_SEXO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "PY"."SP_AGREGAR_SEXO" 
   (NOMBRE VARCHAR2)
  	IS     	 
  	BEGIN
      	INSERT INTO SEXO
      	VALUES(SQ_SEXO.nextval,NOMBRE);
  	END SP_AGREGAR_SEXO;

/
--------------------------------------------------------
--  DDL for Procedure SP_AGREGAR_TIPO_DOC_EXP
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "PY"."SP_AGREGAR_TIPO_DOC_EXP" 
(NOMBRE VARCHAR2 )
IS
BEGIN
INSERT INTO tipo_doc_exp VALUES(SQ_TIPO_DOC_EXP.nextval, NOMBRE , 'A');
END SP_AGREGAR_TIPO_DOC_EXP;

/
--------------------------------------------------------
--  DDL for Procedure SP_AGREGAR_TIPO_DOCUMENTO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "PY"."SP_AGREGAR_TIPO_DOCUMENTO" 
   (NOMBRE VARCHAR2)
  	IS     	 
  	BEGIN
      	INSERT INTO tipo_documento
      	VALUES(SQ_TIPO_DOCUMENTO.nextval,NOMBRE);
  	END SP_AGREGAR_TIPO_DOCUMENTO;

/
--------------------------------------------------------
--  DDL for Procedure SP_AGREGAR_TIPO_ORGANIZACION
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "PY"."SP_AGREGAR_TIPO_ORGANIZACION" 
(NOMBRE VARCHAR2 , ID_CLASIF_ORG NUMBER  )
IS
BEGIN
INSERT INTO TIPO_ORGANIZACION VALUES(SQ_TIPO_ORGANIZACION.nextval, NOMBRE , id_clasif_org , 'A');
END SP_AGREGAR_TIPO_ORGANIZACION;

/
--------------------------------------------------------
--  DDL for Function SF_NOMBRE_EST_CIVIL
--------------------------------------------------------

  CREATE OR REPLACE FUNCTION "PY"."SF_NOMBRE_EST_CIVIL" (ID_ESTADO_CIVIL NUMBER) 
RETURN VARCHAR2
IS 
NOMBRE_EST_CIVIL VARCHAR2(60);
BEGIN
SELECT NOMBRE INTO NOMBRE_EST_CIVIL FROM ESTADO_CIVIL
         WHERE ID_ESTADO_CIVIL = ID_ESTADO_CIVIL;
RETURN NOMBRE_EST_CIVIL;
END SF_NOMBRE_EST_CIVIL;

/
--------------------------------------------------------
--  DDL for Function SF_NOMBRE_PERSONA
--------------------------------------------------------

  CREATE OR REPLACE FUNCTION "PY"."SF_NOMBRE_PERSONA" (ID_PERSONA NUMBER) 
RETURN VARCHAR2
IS 
NOMBRE_PERSONA VARCHAR2(180);
BEGIN
SELECT NOMBRES || ' ' || APELLIDO_PATER || ' ' || APELLIDO_MATER INTO NOMBRE_PERSONA FROM PERSONA
         WHERE ID_PERSONA = ID_PERSONA;
RETURN NOMBRE_PERSONA;
END SF_NOMBRE_PERSONA;

/
--------------------------------------------------------
--  DDL for Function SF_NOMBRE_SEXO
--------------------------------------------------------

  CREATE OR REPLACE FUNCTION "PY"."SF_NOMBRE_SEXO" (ID_SEXO NUMBER) 
RETURN VARCHAR2
IS 
NOMBRE_SEXO VARCHAR2(60);
BEGIN
SELECT NOMBRE INTO NOMBRE_SEXO FROM SEXO
         WHERE ID_SEXO = ID_SEXO;
RETURN NOMBRE_SEXO;
END SF_NOMBRE_SEXO;

/
--------------------------------------------------------
--  DDL for Function SF_NOMBRE_TIPO_ORG
--------------------------------------------------------

  CREATE OR REPLACE FUNCTION "PY"."SF_NOMBRE_TIPO_ORG" (ID_TIPO_ORG NUMBER) 
RETURN VARCHAR2
IS 
NOMBRE_ORG VARCHAR2(60);
BEGIN
SELECT NOMBRE INTO NOMBRE_ORG FROM TIPO_ORGANIZACION
         WHERE ID_TIPO_ORG = ID_TIPO_ORG;
RETURN NOMBRE_ORG;
END SF_NOMBRE_TIPO_ORG;

/
--------------------------------------------------------
--  DDL for Function SF_NOMBRE_USUARIOS
--------------------------------------------------------

  CREATE OR REPLACE FUNCTION "PY"."SF_NOMBRE_USUARIOS" (ID_USUARIOS NUMBER) 
RETURN VARCHAR2
IS 
NOMBRE_USUARIOS VARCHAR2(60);
BEGIN
SELECT NOMBRE INTO NOMBRE_USUARIOS FROM USUARIOS
         WHERE ID_USUARIOS = ID_USUARIOS;
RETURN NOMBRE_USUARIOS;
END SF_NOMBRE_USUARIOS;

/
--------------------------------------------------------
--  Constraints for Table TIPO_ORGANIZACION
--------------------------------------------------------

  ALTER TABLE "PY"."TIPO_ORGANIZACION" ADD UNIQUE ("NOMBRE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PY"."TIPO_ORGANIZACION" ADD PRIMARY KEY ("ID_TIPO_ORG")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PY"."TIPO_ORGANIZACION" MODIFY ("ESTADO" NOT NULL ENABLE);
  ALTER TABLE "PY"."TIPO_ORGANIZACION" MODIFY ("ID_CLASIF_ORG" NOT NULL ENABLE);
  ALTER TABLE "PY"."TIPO_ORGANIZACION" MODIFY ("NOMBRE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TIPO_DOCUMENTO
--------------------------------------------------------

  ALTER TABLE "PY"."TIPO_DOCUMENTO" ADD PRIMARY KEY ("ID_TIPO_DOC")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PY"."TIPO_DOCUMENTO" MODIFY ("NOMBRE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USUARIOS
--------------------------------------------------------

  ALTER TABLE "PY"."USUARIOS" MODIFY ("ESTADO" NOT NULL ENABLE);
  ALTER TABLE "PY"."USUARIOS" ADD PRIMARY KEY ("ID_USUARIOS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PY"."USUARIOS" MODIFY ("NOMBRE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ORGANIZACION_PERSONA
--------------------------------------------------------

  ALTER TABLE "PY"."ORGANIZACION_PERSONA" MODIFY ("ID_ASOCIADO" NOT NULL ENABLE);
  ALTER TABLE "PY"."ORGANIZACION_PERSONA" MODIFY ("ID_ORGANIZACION" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PERSONA
--------------------------------------------------------

  ALTER TABLE "PY"."PERSONA" ADD UNIQUE ("NUMERO_DOC")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PY"."PERSONA" ADD PRIMARY KEY ("ID_PERSONA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PY"."PERSONA" MODIFY ("FEC_NAC" NOT NULL ENABLE);
  ALTER TABLE "PY"."PERSONA" MODIFY ("ID_SEXO" NOT NULL ENABLE);
  ALTER TABLE "PY"."PERSONA" MODIFY ("NUMERO_DOC" NOT NULL ENABLE);
  ALTER TABLE "PY"."PERSONA" MODIFY ("ID_TIPO_DOC" NOT NULL ENABLE);
  ALTER TABLE "PY"."PERSONA" MODIFY ("APELLIDO_MATER" NOT NULL ENABLE);
  ALTER TABLE "PY"."PERSONA" MODIFY ("APELLIDO_PATER" NOT NULL ENABLE);
  ALTER TABLE "PY"."PERSONA" MODIFY ("NOMBRES" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CLASIF_ORGANIZACION
--------------------------------------------------------

  ALTER TABLE "PY"."CLASIF_ORGANIZACION" ADD UNIQUE ("NOMBRE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PY"."CLASIF_ORGANIZACION" ADD PRIMARY KEY ("ID_CLASIF_ORG")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PY"."CLASIF_ORGANIZACION" MODIFY ("ESTADO" NOT NULL ENABLE);
  ALTER TABLE "PY"."CLASIF_ORGANIZACION" MODIFY ("NOMBRE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CARGO
--------------------------------------------------------

  ALTER TABLE "PY"."CARGO" ADD UNIQUE ("NOMBRE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PY"."CARGO" ADD PRIMARY KEY ("ID_CARGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PY"."CARGO" MODIFY ("ESTADO" NOT NULL ENABLE);
  ALTER TABLE "PY"."CARGO" MODIFY ("NOMBRE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TIPO_DOC_EXP
--------------------------------------------------------

  ALTER TABLE "PY"."TIPO_DOC_EXP" ADD UNIQUE ("NOMBRE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PY"."TIPO_DOC_EXP" ADD PRIMARY KEY ("ID_TIPO_DOC_EXP")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PY"."TIPO_DOC_EXP" MODIFY ("ESTADO" NOT NULL ENABLE);
  ALTER TABLE "PY"."TIPO_DOC_EXP" MODIFY ("NOMBRE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ORGANO_DIRECTIVA
--------------------------------------------------------

  ALTER TABLE "PY"."ORGANO_DIRECTIVA" ADD PRIMARY KEY ("ID_ORGANO_DIRECTIVO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PY"."ORGANO_DIRECTIVA" MODIFY ("TIEMPO" NOT NULL ENABLE);
  ALTER TABLE "PY"."ORGANO_DIRECTIVA" MODIFY ("FEC_FIN" NOT NULL ENABLE);
  ALTER TABLE "PY"."ORGANO_DIRECTIVA" MODIFY ("FEC_INICIO" NOT NULL ENABLE);
  ALTER TABLE "PY"."ORGANO_DIRECTIVA" MODIFY ("ID_ORGANIZACION" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CONTROL
--------------------------------------------------------

  ALTER TABLE "PY"."CONTROL" ADD PRIMARY KEY ("ID_CONTROL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PY"."CONTROL" MODIFY ("DATOS" NOT NULL ENABLE);
  ALTER TABLE "PY"."CONTROL" MODIFY ("ACCION" NOT NULL ENABLE);
  ALTER TABLE "PY"."CONTROL" MODIFY ("TABLA" NOT NULL ENABLE);
  ALTER TABLE "PY"."CONTROL" MODIFY ("USUARIO" NOT NULL ENABLE);
  ALTER TABLE "PY"."CONTROL" MODIFY ("ID_CONTROL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SEXO
--------------------------------------------------------

  ALTER TABLE "PY"."SEXO" ADD PRIMARY KEY ("ID_SEXO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PY"."SEXO" MODIFY ("NOMBRE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EXPEDIENTE
--------------------------------------------------------

  ALTER TABLE "PY"."EXPEDIENTE" ADD PRIMARY KEY ("ID_EXPEDIENTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PY"."EXPEDIENTE" MODIFY ("ESTADO" NOT NULL ENABLE);
  ALTER TABLE "PY"."EXPEDIENTE" MODIFY ("FECHA_REGISTRO" NOT NULL ENABLE);
  ALTER TABLE "PY"."EXPEDIENTE" MODIFY ("ID_SOLICITANTE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ORGANO_DIRECTIVA_DET
--------------------------------------------------------

  ALTER TABLE "PY"."ORGANO_DIRECTIVA_DET" ADD PRIMARY KEY ("ID_ORGANO_DIRECTIVO_DET")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PY"."ORGANO_DIRECTIVA_DET" MODIFY ("ESTADO" NOT NULL ENABLE);
  ALTER TABLE "PY"."ORGANO_DIRECTIVA_DET" MODIFY ("ID_CARGO" NOT NULL ENABLE);
  ALTER TABLE "PY"."ORGANO_DIRECTIVA_DET" MODIFY ("ID_PERSONA" NOT NULL ENABLE);
  ALTER TABLE "PY"."ORGANO_DIRECTIVA_DET" MODIFY ("ID_ORGANO_DIRECTIVO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ESTADO_CIVIL
--------------------------------------------------------

  ALTER TABLE "PY"."ESTADO_CIVIL" ADD PRIMARY KEY ("ID_ESTADO_CIVIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PY"."ESTADO_CIVIL" MODIFY ("NOMBRE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ORGANIZACION
--------------------------------------------------------

  ALTER TABLE "PY"."ORGANIZACION" ADD UNIQUE ("NUM_PART_REGISTRAL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PY"."ORGANIZACION" ADD PRIMARY KEY ("ID_ORGANIZACION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PY"."ORGANIZACION" MODIFY ("FECHA_INICIO" NOT NULL ENABLE);
  ALTER TABLE "PY"."ORGANIZACION" MODIFY ("NUM_PART_REGISTRAL" NOT NULL ENABLE);
  ALTER TABLE "PY"."ORGANIZACION" MODIFY ("NOMBRE_ORG" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DOCUMENTOS
--------------------------------------------------------

  ALTER TABLE "PY"."DOCUMENTOS" ADD PRIMARY KEY ("ID_DOCUMENTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PY"."DOCUMENTOS" MODIFY ("ESTADO" NOT NULL ENABLE);
  ALTER TABLE "PY"."DOCUMENTOS" MODIFY ("ARCHIVO" NOT NULL ENABLE);
  ALTER TABLE "PY"."DOCUMENTOS" MODIFY ("ID_TIPO_DOC_EXP" NOT NULL ENABLE);
  ALTER TABLE "PY"."DOCUMENTOS" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "PY"."DOCUMENTOS" MODIFY ("ID_ORGANIZACION" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table DOCUMENTOS
--------------------------------------------------------

  ALTER TABLE "PY"."DOCUMENTOS" ADD FOREIGN KEY ("ID_ORGANIZACION")
	  REFERENCES "PY"."ORGANIZACION" ("ID_ORGANIZACION") ENABLE;
  ALTER TABLE "PY"."DOCUMENTOS" ADD FOREIGN KEY ("ID_TIPO_DOC_EXP")
	  REFERENCES "PY"."TIPO_DOC_EXP" ("ID_TIPO_DOC_EXP") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EXPEDIENTE
--------------------------------------------------------

  ALTER TABLE "PY"."EXPEDIENTE" ADD FOREIGN KEY ("ID_SOLICITANTE")
	  REFERENCES "PY"."PERSONA" ("ID_PERSONA") ENABLE;
  ALTER TABLE "PY"."EXPEDIENTE" ADD FOREIGN KEY ("ID_USUARIO_REVISION")
	  REFERENCES "PY"."USUARIOS" ("ID_USUARIOS") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ORGANIZACION
--------------------------------------------------------

  ALTER TABLE "PY"."ORGANIZACION" ADD FOREIGN KEY ("ID_EXPEDIENTE")
	  REFERENCES "PY"."EXPEDIENTE" ("ID_EXPEDIENTE") ENABLE;
  ALTER TABLE "PY"."ORGANIZACION" ADD FOREIGN KEY ("ID_TIPO_ORG")
	  REFERENCES "PY"."TIPO_ORGANIZACION" ("ID_TIPO_ORG") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ORGANIZACION_PERSONA
--------------------------------------------------------

  ALTER TABLE "PY"."ORGANIZACION_PERSONA" ADD FOREIGN KEY ("ID_ORGANIZACION")
	  REFERENCES "PY"."ORGANIZACION" ("ID_ORGANIZACION") ENABLE;
  ALTER TABLE "PY"."ORGANIZACION_PERSONA" ADD FOREIGN KEY ("ID_ASOCIADO")
	  REFERENCES "PY"."PERSONA" ("ID_PERSONA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ORGANO_DIRECTIVA
--------------------------------------------------------

  ALTER TABLE "PY"."ORGANO_DIRECTIVA" ADD FOREIGN KEY ("ID_ORGANIZACION")
	  REFERENCES "PY"."ORGANIZACION" ("ID_ORGANIZACION") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ORGANO_DIRECTIVA_DET
--------------------------------------------------------

  ALTER TABLE "PY"."ORGANO_DIRECTIVA_DET" ADD FOREIGN KEY ("ID_ORGANO_DIRECTIVO")
	  REFERENCES "PY"."ORGANO_DIRECTIVA" ("ID_ORGANO_DIRECTIVO") ENABLE;
  ALTER TABLE "PY"."ORGANO_DIRECTIVA_DET" ADD FOREIGN KEY ("ID_PERSONA")
	  REFERENCES "PY"."PERSONA" ("ID_PERSONA") ENABLE;
  ALTER TABLE "PY"."ORGANO_DIRECTIVA_DET" ADD FOREIGN KEY ("ID_CARGO")
	  REFERENCES "PY"."CARGO" ("ID_CARGO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PERSONA
--------------------------------------------------------

  ALTER TABLE "PY"."PERSONA" ADD FOREIGN KEY ("ID_TIPO_DOC")
	  REFERENCES "PY"."TIPO_DOCUMENTO" ("ID_TIPO_DOC") ENABLE;
  ALTER TABLE "PY"."PERSONA" ADD FOREIGN KEY ("ID_SEXO")
	  REFERENCES "PY"."SEXO" ("ID_SEXO") ENABLE;
  ALTER TABLE "PY"."PERSONA" ADD FOREIGN KEY ("ID_ESTADO_CIVIL")
	  REFERENCES "PY"."ESTADO_CIVIL" ("ID_ESTADO_CIVIL") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TIPO_ORGANIZACION
--------------------------------------------------------

  ALTER TABLE "PY"."TIPO_ORGANIZACION" ADD FOREIGN KEY ("ID_CLASIF_ORG")
	  REFERENCES "PY"."CLASIF_ORGANIZACION" ("ID_CLASIF_ORG") ENABLE;
